pipeline{
    agent any

    tools{
        maven 'M2_HOME'
    }

    stages{
        stage("sonarQube scan"){
            steps {
                withSonarQubeEnv(credentialsId:'sonarQube-id', installationName:'SonarQube') {
                   sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=franck-Kone_geo-app'
                }
            }
        }
        stage('maven') {
            steps {
                sh 'mvn clean validate compile install test package'
            }
        }

        stage('upload artifact') {
            steps {
                sh 'curl -uadmin:AP8gcgmmset5jeYChTJYDN6XmDd -T \
                target/bio*.jar \
                "http://ec2-54-159-27-1.compute-1.amazonaws.com:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'
            }  
        }
    }
}